// Actual checked-in migration SQL is hashed at runtime; no acceptance-output snapshot.
pub(crate) const NATIVE_MIGRATIONS: &[(&str, &[u8])] = &[
    (
        "001_initial",
        include_bytes!("../../../../../store/migrations/001_initial.sql"),
    ),
    (
        "002_runtime_ledger",
        include_bytes!("../../../../../store/migrations/002_runtime_ledger.sql"),
    ),
    (
        "003_evidence_isolation",
        include_bytes!("../../../../../store/migrations/003_evidence_isolation.sql"),
    ),
    (
        "004_automation_campaigns",
        include_bytes!("../../../../../store/migrations/004_automation_campaigns.sql"),
    ),
    (
        "005_automation_operations",
        include_bytes!("../../../../../store/migrations/005_automation_operations.sql"),
    ),
    (
        "006_multiprocess_automation",
        include_bytes!("../../../../../store/migrations/006_multiprocess_automation.sql"),
    ),
    (
        "007_campaign_lineage_backfill",
        include_bytes!("../../../../../store/migrations/007_campaign_lineage_backfill.sql"),
    ),
    (
        "008_reviewer_identity_backfill",
        include_bytes!("../../../../../store/migrations/008_reviewer_identity_backfill.sql"),
    ),
    (
        "009_resource_admission_queue",
        include_bytes!("../../../../../store/migrations/009_resource_admission_queue.sql"),
    ),
    (
        "010_resource_admission_metadata",
        include_bytes!("../../../../../store/migrations/010_resource_admission_metadata.sql"),
    ),
    (
        "011_workspace_lineage",
        include_bytes!("../../../../../store/migrations/011_workspace_lineage.sql"),
    ),
    (
        "012_schema_metadata_consistency",
        include_bytes!("../../../../../store/migrations/012_schema_metadata_consistency.sql"),
    ),
    (
        "013_campaign_telemetry",
        include_bytes!("../../../../../store/migrations/013_campaign_telemetry.sql"),
    ),
    (
        "014_legacy_native_lineage",
        include_bytes!("../../../../../store/migrations/014_legacy_native_lineage.sql"),
    ),
    (
        "015_submission_boundary_hardening",
        include_bytes!("../../../../../store/migrations/015_submission_boundary_hardening.sql"),
    ),
    (
        "016_submission_delivery_leases",
        include_bytes!("../../../../../store/migrations/016_submission_delivery_leases.sql"),
    ),
    (
        "017_trusted_evidence_and_response_consumption",
        include_bytes!(
            "../../../../../store/migrations/017_trusted_evidence_and_response_consumption.sql"
        ),
    ),
    (
        "018_append_only_receipt_ledger",
        include_bytes!("../../../../../store/migrations/018_append_only_receipt_ledger.sql"),
    ),
    (
        "019_effective_receipt_ledger",
        include_bytes!("../../../../../store/migrations/019_effective_receipt_ledger.sql"),
    ),
    (
        "020_monotonic_receipt_qualification",
        include_bytes!("../../../../../store/migrations/020_monotonic_receipt_qualification.sql"),
    ),
    (
        "021_job_lease_fencing",
        include_bytes!("../../../../../store/migrations/021_job_lease_fencing.sql"),
    ),
    (
        "022_campaign_attempt_fencing",
        include_bytes!("../../../../../store/migrations/022_campaign_attempt_fencing.sql"),
    ),
    (
        "023_workspace_retention_qualification",
        include_bytes!("../../../../../store/migrations/023_workspace_retention_qualification.sql"),
    ),
    (
        "024_submission_outbox_delivery_kind",
        include_bytes!("../../../../../store/migrations/024_submission_outbox_delivery_kind.sql"),
    ),
    (
        "025_external_autonomous_submission_handoff",
        include_bytes!(
            "../../../../../store/migrations/025_external_autonomous_submission_handoff.sql"
        ),
    ),
];
