import assert from 'node:assert/strict';
import test from 'node:test';
import { createSqliteReceiptLedger } from '../../../paper-adapters/persistence/sqlite-receipt-ledger.mjs';
import { createSqliteSubmissionDeliveryStore } from '../../../paper-adapters/submission/sqlite-delivery-store.mjs';
import { hashRecord } from '../../../workflow-kernel/record-hash.mjs';
import { buildExecutorResponseIntake, buildSubmissionRedrivePlan } from '../../../paper-domain/submission/delivery-runtime.mjs';
import { fixedClock, temporaryDirectory, temporaryStore } from './test-support.mjs';

test('submission.delivery-runtime recovers after restart, deduplicates responses and dead-letters retries', async (t) => {
  const root = await temporaryDirectory(t);
  const store = temporaryStore(root);
  const clock = fixedClock();
  const ledger = createSqliteReceiptLedger({ store, clock });
  let delivery = createSqliteSubmissionDeliveryStore({ store, receiptLedger: ledger, clock });
  const authorization = { status: 'submission_dispatch_authorization_ready', submissionDispatchAuthorizationHash: 'h', provider: 'provider', accountId: 'account', nonce: 'nonce', attempt: 1 };
  const message = delivery.enqueue({ paperId: 'p', dispatchAuthorization: authorization, payload: {} });
  assert.equal(delivery.recoverPending().length, 1);
  const failedResponse = { responseId: 'r', outcome: 'failed', dispatchAuthorizationHash: 'h', provider: 'provider', accountId: 'account', performedAt: '2026-07-10T08:00:00.000Z', attempt: 1 };
  delivery.recordResponse({ messageId: message.message_id, response: failedResponse });
  delivery = createSqliteSubmissionDeliveryStore({ store, receiptLedger: ledger, clock });
  assert.equal(delivery.recoverPending().length, 0);
  delivery.recordResponse({ messageId: message.message_id, response: failedResponse });
  assert.throws(() => delivery.recordResponse({ messageId: message.message_id, response: { ...failedResponse, outcome: 'cancelled' } }), /duplicate executor response conflict/);
  assert.equal(delivery.scheduleRedrive({ messageId: message.message_id, maximumAttempts: 1 }).status, 'submission_dead_letter_recorded');
});

test('submission.delivery-runtime verifies provider receipts and serializes release locks', async (t) => {
  const root = await temporaryDirectory(t);
  const store = temporaryStore(root);
  const clock = fixedClock();
  const ledger = createSqliteReceiptLedger({ store, clock });
  const delivery = createSqliteSubmissionDeliveryStore({ store, receiptLedger: ledger, clock });
  const authorization = { status: 'submission_dispatch_authorization_ready', submissionDispatchAuthorizationHash: 'h2', provider: 'provider', accountId: 'account', nonce: 'nonce-2', attempt: 1, expectedArtifactHashes: ['sha256:artifact'] };
  const message = delivery.enqueue({ paperId: 'p2', dispatchAuthorization: authorization, payload: {} });
  const lock = delivery.acquireReleaseLock({ paperId: 'p2', messageId: message.message_id, lockToken: 'lock-2' });
  assert.equal(delivery.acquireReleaseLock({ paperId: 'p2', messageId: message.message_id, lockToken: 'competing-lock' }), null);
  const providerReceipt = { provider: 'provider', accountId: 'account', submissionId: 'external-1', dispatchAuthorizationHash: 'h2', uploadedArtifactHashes: ['sha256:artifact'] };
  const providerReceiptHash = hashRecord('ProviderSubmissionReceipt', providerReceipt);
  const response = { responseId: 'r2', outcome: 'submitted', dispatchAuthorizationHash: 'h2', provider: 'provider', accountId: 'account', submissionId: 'external-1', providerReceipt, providerReceiptHash, uploadedArtifactHashes: ['sha256:artifact'], performedAt: '2026-07-10T08:00:00.000Z', attempt: 1 };
  assert.throws(() => delivery.recordResponse({ messageId: message.message_id, response: { ...response, responseId: 'bad', providerReceiptHash: 'sha256:bad' } }), /provider_receipt_hash_mismatch/);
  delivery.recordResponse({ messageId: message.message_id, response });
  assert.throws(() => delivery.release({ paperId: 'p2', lockToken: lock.lock_token, releaseLock: { status: 'submission_release_locked' } }));
  const responseIntake = buildExecutorResponseIntake({ dispatchAuthorization: authorization, response });
  const verifiedReleaseLock = { status: 'submission_release_unlocked', reconciliationHash: 'sha256:reconciliation', dispatchAuthorizationHash: 'h2', responseIntakeHash: responseIntake.executorResponseIntakeHash };
  const released = delivery.release({ paperId: 'p2', lockToken: lock.lock_token, releaseLock: verifiedReleaseLock });
  assert.equal(released.status, 'released');
  assert.throws(() => delivery.release({ paperId: 'p2', lockToken: lock.lock_token, releaseLock: verifiedReleaseLock }), /active release lock missing/);
});

test('submission redrive persists reauthorization requirement and enqueues only a fresh eligible dispatch', async (t) => {
  const root = await temporaryDirectory(t);
  const store = temporaryStore(root);
  let milliseconds = Date.parse('2026-07-10T08:00:00.000Z');
  const clock = { now: () => new Date(milliseconds), nowIso: () => new Date(milliseconds).toISOString() };
  const ledger = createSqliteReceiptLedger({ store, clock });
  const delivery = createSqliteSubmissionDeliveryStore({ store, receiptLedger: ledger, clock });
  const authorization = { status: 'submission_dispatch_authorization_ready', submissionDispatchAuthorizationHash: 'dispatch-1', provider: 'provider', accountId: 'account', nonce: 'nonce-1', attempt: 1 };
  const message = delivery.enqueue({ paperId: 'p-redrive', dispatchAuthorization: authorization, payload: {} });
  const response = { responseId: 'failed-1', outcome: 'failed', dispatchAuthorizationHash: 'dispatch-1', provider: 'provider', accountId: 'account', performedAt: clock.nowIso(), attempt: 1 };
  delivery.recordResponse({ messageId: message.message_id, response });
  const responseIntake = buildExecutorResponseIntake({ dispatchAuthorization: authorization, response });
  const redrivePlan = buildSubmissionRedrivePlan({ dispatchAuthorization: authorization, responseIntake });
  const scheduled = delivery.scheduleRedrive({ messageId: message.message_id, redrivePlan, maximumAttempts: 3, delaySeconds: 1 });
  assert.equal(scheduled.status, 'submission_redrive_reauthorization_required');
  assert.equal(delivery.recoverPending().length, 0);
  const freshPayload = { ...authorization, nonce: 'nonce-2', redrivePlanHash: redrivePlan.submissionRedrivePlanHash, attempt: 2, replayKey: `sha256:${'1'.repeat(64)}`, actionScopeKey: `sha256:${'2'.repeat(64)}`, dispatchCycleHash: `sha256:${'3'.repeat(64)}`, liveAuthorizationHash: `sha256:${'4'.repeat(64)}`, responseDueAt: '2026-07-10T09:00:00.000Z', providerCapabilityVerificationReceiptHash: `sha256:${'5'.repeat(64)}`, portalRoute: '/submit' };
  delete freshPayload.submissionDispatchAuthorizationHash;
  const fresh = { ...freshPayload, submissionDispatchAuthorizationHash: hashRecord('SubmissionDispatchAuthorization', freshPayload) };
  assert.throws(() => delivery.enqueueRedrive({ previousMessageId: message.message_id, dispatchAuthorization: fresh }), /eligibility time not reached/);
  milliseconds += 1000;
  const reusedNoncePayload = { ...freshPayload, nonce: 'nonce-1' };
  const reusedNonce = { ...reusedNoncePayload, submissionDispatchAuthorizationHash: hashRecord('SubmissionDispatchAuthorization', reusedNoncePayload) };
  assert.throws(() => delivery.enqueueRedrive({ previousMessageId: message.message_id, dispatchAuthorization: reusedNonce }), /nonce must be fresh/);
  const receipt = delivery.enqueueRedrive({ previousMessageId: message.message_id, dispatchAuthorization: fresh });
  assert.equal(receipt.status, 'submission_redrive_enqueued_with_fresh_authorization');
  assert.equal(delivery.getOutbox(message.message_id).status, 'superseded');
  assert.equal(delivery.getOutbox(receipt.messageId).status, 'pending');
});
